name: Next.js CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps: 
    - users: actions/checkout@v2
    - name: Use Next.js ${{matrix.node-version}}
      users: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: 
        npm i
        npm run build

