name: Node.js CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    # runs-on: ubuntu-22.04
    runs-on: self-hosted

    steps: 
    - name: Adjust Permissions
      run: |
        chmod -R 755 /var/www/reklaminiai/reklaminiai-client/_work/reklaminiai-client/reklaminiai-client/build/server/chunks
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: Create .env file
      run: |
        echo "NEXT_PUBLIC_ADMIN_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY3MzY5ODgwNCwiZXhwIjoxNjczNzAyNDA0fQ.lLoBICnvCARJYrISbzGsIGQurFW_e9NySot3V37lTy8" > .env
        echo "NEXT_PUBLIC_API_URL=https://api.reklaminiai.lt" >> .env
    - name: Removing node_modules folder
      run: 
        rm -rf node_modules/
    - name: Installing dependencies
      run: 
        npm i
    - name: Building application
      run:
        npm run build
   