name: Node.js CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    # runs-on: ubuntu-22.04
    runs-on: self-hosted

    steps: 
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - run: 
        # npm install -g next
        npm i
        npm run build

  create-envfile:
 
    runs-on: ubuntu-20.4
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        envkey_NEXT_PUBLIC_ADMIN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY3MzY5ODgwNCwiZXhwIjoxNjczNzAyNDA0fQ.lLoBICnvCARJYrISbzGsIGQurFW_e9NySot3V37lTy8"
        envkey_NEXT_PUBLIC_API_URL: "https://api.reklaminiai.lt"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        # envkey_VARIABLE: ${{ vars.SOME_ACTION_VARIABLE }}
        # some_other_variable: foobar
        directory: <directory_name>
        file_name: .env
        fail_on_empty: false
        sort_keys: false

